GET http://localhost:8082/notifications/2
Accept: application/json
X-Account: login
X-Account-Id: 1

###
GET http://localhost:8082/notifications
Accept: application/json
X-Account: login
X-Account-Id: 3

###
PATCH http://localhost:8082/notifications/2?read=true
Accept: application/json
X-Account: login
X-Account-Id: 1

###