GET http://localhost:8082/templates/2
Accept: application/json

###

GET http://localhost:8082/templates
Accept: application/json

###

POST http://localhost:8082/templates
Content-Type: application/json

{
  "name": "mailVerification",
  "message": "",
  "HTML": true
}

###

PUT http://localhost:8082/templates/2
Content-Type: application/json

{
  "name": "auth",
  "message": "Thanks for creating account in ViMo service. Good",
  "HTML": false
}

###

DELETE http://localhost:8082/templates/1
Accept: application/json

###

POST http://localhost:8082/templates/auth/send?type=internal
Content-Type: application/json

{
  "resource_id": 1,
  "tag": "account",
  "recipients": [
    1,
    2
  ],
  "data": {}
}

###
POST http://localhost:8082/templates/mailVerification/send?type=email
Content-Type: application/json

{
  "recipients": [
    "example@example.com"
  ],
  "data": {
    "user": "Mateusz",
    "userId": "2",
    "code": "1235"
  }
}
