GET http://localhost:8082/templates/2
Accept: application/json

###

POST http://localhost:8082/templates
Content-Type: application/json

{
  "name": "auth",
  "message": "Thanks for creating account in ViMo service",
  "HTML": false
}

###

PUT http://localhost:8082/templates/2
Content-Type: application/json

{
  "name": "auth",
  "message": "Thanks for creating account in ViMo service. Good",
  "HTML": false
}

###

DELETE http://localhost:8082/templates/1
Accept: application/json

###
