GET http://localhost:8082/templates/2
Accept: application/json

###

GET http://localhost:8082/templates
Accept: application/json

###

POST http://localhost:8082/templates
Content-Type: application/json

{
  "name": "commentLike",
  "message": "User {{.user}} liked your comment",
  "HTML": false
}

###

PUT http://localhost:8082/templates/2
Content-Type: application/json

{
  "name": "auth",
  "message": "Thanks for creating account in ViMo service. Good",
  "HTML": false
}

###

DELETE http://localhost:8082/templates/1
Accept: application/json

###

POST http://localhost:8082/templates/commentLike/send?type=internal
Content-Type: application/json

{
  "resource": "comment",
  "resource_id": 26,
  "tag": "movie/299534",
  "recipients": [
    3
  ],
  "data": {
    "user": "User"
  }
}

###
POST http://localhost:8082/templates/mailVerification/send?type=email
Content-Type: application/json

{
  "recipients": [
    "email@gmail.com"
  ],
  "data": {
    "user": "user",
    "userId": "2",
    "code": "1235"
  }
}
